paypal:
  baseUrl: https://api-3t.sandbox.paypal.com
  signature: AiS5Cksed0F3o2HDVub1DjPd188aAJAsUegdP1YDXsAYJq4OavPWNCOf
  user: sb-by43uc25735211_api1.business.example.com
  pwd: 9L95ZAPQ2ZPSN4GW
server:
  port : 8081
#spring:
#  security:
#    oauth2:
#      client:
#        provider:
#          wso2:
#            authorization-uri: https://localhost:9443/oauth2/authorize
#            jwk-set-uri: https://localhost:9443/oauth2/jwks
#            token-uri: https://localhost:9443/oauth2/token
#            user-info-uri: https://localhost:9443/oauth2/userinfo
#        registration:
#          google:
#            client-id: 698609981306-mn6nv30uo4mbaf2hbujf6mhm6djjh6mg.apps.googleusercontent.com
#            client-secret: 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
#          wso2:
#            client-id: GATuEJm1X83vq7QbuphdDDjQwhsa
#            client-secret: x00xGfGeexAbaZJQGF9hMHf4pE8a
