paypal:
  baseUrl: ${BASEURL}
  signature: ${SIGNATURE}
  user: ${USER}
  pwd: ${PWD}
server:
  port : 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK}
